[package]
name = "daredevil-small"
version = "0.1.0"
authors = ["Tmplt <tmplt@dragons.rocks>"]
edition = "2018"

[dependencies]
cortex-m = "0.5.0"
panic-halt = "0.2.0"
cortex-m-rt = "0.6.3"
s32k144 = { git = "https://github.com/Tmplt/s32k144.rs.git" }
